defaults
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
            author: "Alpha59"
            desc: "This is a descriptional Test!"