subtitle: A test page
defaults:
    -
        values:
            layout: docs
background: "http://traivan98.xyz/atom-preview/image-style/images/dark_bg.jpg"
categories_pages: [Reference, Meta, About]
# These are the sections on the home page which need to be filled in,
# every even one gets an image (be safe, have 4-5 images).
content:
    -
        title: Section 1
        href: section1
        desc: The first section
        subs:
            -
                title: Sub Heading 1
                desc: The first subheading under section 1
            -
                title: Sub Heading 2
                desc: The second subheader under section 1
    -
        title: Section 2
        background: "img/intro-bg.jpg"
        href: section2
        desc: The section section
        subs:
            -
                title: Sub Heading 1
                desc: The first subheading under section 2
            -
                title: Sub Heading 2
                desc: The second subheader under section 2
            -
                title: Sub Heading 3
                desc: The second subheader under section 3
    -
        title: Section 3
        href: section3
        desc: The third section
        subs:
            -
                title: Sub Heading 1
                desc: The first subheading under section 3
            -
                title: Sub Heading 2
                desc: The second subheader under section 3
downloads_background: "img/downloads-bg.jpg"
